---
name: ActionLint
on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']
  workflow_dispatch:
permissions: {}
jobs:
  actionlint:
    uses: ./.github/workflows/reusable-actionlint.yml
    permissions:
      checks: write
      contents: read
      pull-requests: read
