---
name: PR checks
on:
  pull_request:
    types: [opened, edited, synchronize, reopened, unlocked]
permissions: {}
jobs:
  check-conventional-commit:
    uses: ./.github/workflows/reusable-pr.yml
    permissions:
      contents: read
