---
name: PR checks (reusable)
on:
  workflow_call:
    inputs:
      python-version:
        description: Python version for commitizen
        required: false
        type: string
        default: "3.x"
permissions: {}
jobs:
  check-conventional-commit:
    name: Check commit messages
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: ${{ inputs.python-version }}
      - run: pip install commitizen
      - name: Check commit messages
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: cz check --rev-range "$BASE_SHA..$HEAD_SHA"
