---
name: Add issue to project (reusable)
on:
  workflow_call:
    secrets:
      POLARION_GITHUB_APP_ID:
        required: true
      POLARION_GITHUB_APP_PRIVATE_KEY:
        required: true
    inputs:
      project-number:
        description: The GitHub project number to add the issue to
        required: true
        type: string
permissions: {}
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    environment: github-project
    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf  # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.POLARION_GITHUB_APP_ID }}
          private-key: ${{ secrets.POLARION_GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e  # v1.0.2
        with:
          project-url: https://github.com/orgs/SchweizerischeBundesbahnen/projects/${{ inputs.project-number }}
          github-token: ${{ steps.app-token.outputs.token }}
