---
name: Add issue to project (reusable)
on:
  workflow_call:
    secrets:
      POLARION_GITHUB_APP_ID:
        required: true
      POLARION_GITHUB_APP_PRIVATE_KEY:
        required: true
    inputs:
      project-number:
        description: The GitHub project number to add the issue to
        required: true
        type: string
permissions: {}
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3  # v3.1.1
        id: app-token
        with:
          client-id: ${{ secrets.POLARION_GITHUB_APP_ID }}
          private-key: ${{ secrets.POLARION_GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e  # v1.0.2
        with:
          project-url: https://github.com/orgs/${{ github.repository_owner }}/projects/${{ inputs.project-number }}
          github-token: ${{ steps.app-token.outputs.token }}
